/*----------------------------------------------------------------------------*/
/* Copyright (c) 2017-2018 FIRST. All Rights Reserved.                        */
/* Open Source Software - may be modified and shared by FRC teams. The code   */
/* must be accompanied by the FIRST BSD license file in the root directory of */
/* the project.                                                               */
/*----------------------------------------------------------------------------*/

package frc.robot;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
  // For example to map the left and right motors, you could define the
  // following variables to use with your drivetrain subsystem.
  // public static int leftMotor = 1;
  // public static int rightMotor = 2;
  
 // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
 //public static SpeedController liftBubble1;
 //public static SpeedController liftBubble2;
 //public static RobotDrive liftLiftMotors;

 // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

  //Drivetrain
  public static final int DRIVETRAIN_LEFT_FRONT_TALON = 0;
  public static final int DRIVETRAIN_LEFT_BACK_TALON = 1;
  public static final int DRIVETRAIN_RIGHT_FRONT_TALON = 5;
  public static final int DRIVETRAIN_RIGHT_BACK_TALON = 6;
  //Intake
  public static final int INTAKE_TALON_2 = 2;
  //Lift
  public static final int LIFT_TALON_L = 9;
  public static final int LIFT_TALON_R = 8;
  //Pneumatics
  public static final int doubleSolenoid1 = 1;
  public static final int doubleSolenoid2 = 0;
  //Spool/Winch
  public static final int SPOOL_TALON_SP = 3;
  //public static final int SUBSYSTESIDE_POSITION_SPEEDCONTROLLER = PWM Port;

  //Joystick
  public static final int OI_DRIVE_CONTROLLER = 0;
  public static final int OI_AUX_CONTROLLER = 1;
//public static final String lift = null;
  // If you are using multiple modules, make sure to define both the port
  // number and the module. For example you with a rangefinder:
  // public static int rangefinderPort = 1;
  // public static int rangefinderModule = 1;
}
