/*----------------------------------------------------------------------------*/
/* Copyright (c) 2017-2018 FIRST. All Rights Reserved.                        */
/* Open Source Software - may be modified and shared by FRC teams. The code   */
/* must be accompanied by the FIRST BSD license file in the root directory of */
/* the project.                                                               */
/*----------------------------------------------------------------------------*/

package frc.robot;

//import edu.wpi.first.wpilibj.RobotDrive;
//import edu.wpi.first.wpilibj.SpeedController;
//import edu.wpi.first.wpilibj.Talon;
//import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
  // For example to map the left and right motors, you could define the
  // following variables to use with your drivetrain subsystem.
  // public static int leftMotor = 1;
  // public static int rightMotor = 2;
  
 // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
 //public static SpeedController liftBubble1;
 //public static SpeedController liftBubble2;
 //public static RobotDrive liftLiftMotors;

 // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

 public static void init() {
     // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
     //liftBubble1 = new Talon(8);
     //LiveWindow.addActuator("Lift", "Bubble", (Talon) liftBubble1);
     //liftBubble1.setInverted(false);
     //liftBubble2 = new Talon(9);
     //LiveWindow.addActuator("Lift", "Ghost", (Talon) liftBubble2);
     //liftBubble2.setInverted(false);
     //liftLiftMotors = new RobotDrive(liftBubble2, liftBubble1);
     
     //liftLiftMotors.setSafetyEnabled(false);
     //liftLiftMotors.setExpiration(0.1);
     //liftLiftMotors.setSensitivity(0.5);
     //liftLiftMotors.setMaxOutput(1.0);
}

 // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

  //Talons
  public static final int DRIVETRAIN_LEFT_FRONT_TALON = 0;
  public static final int DRIVETRAIN_LEFT_BACK_TALON = 1;
  public static final int DRIVETRAIN_RIGHT_FRONT_TALON = 5;
  public static final int DRIVETRAIN_RIGHT_BACK_TALON = 6;
  public static final int INTAKE_TALON_2 = 2;
  
  //public static final int SUBSYSTESIDE_POSITION_SPEEDCONTROLLER = PWM Port;

  //Joystick
  public static final int OI_DRIVE_CONTROLLER = 0;
public static final int DRIVE_CONTROLLER_MOVE_AXIS = 1;
public static final int DRIVE_CONTROLLER_ROTATE_AXIS = 0;
//public static final String lift = null;
  // If you are using multiple modules, make sure to define both the port
  // number and the module. For example you with a rangefinder:
  // public static int rangefinderPort = 1;
  // public static int rangefinderModule = 1;
}
